---
abstract: 'Minimize cognitive complexity by factoring code into smaller subroutines.'
author:
  - 'Oliver Trosien <mailacc.67890+cpan@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.17'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Critic-Policy-Subroutines-ProhibitExcessCognitiveComplexity
no_index:
  directory:
    - inc
    - t
requires:
  Perl::Critic: 0
version: '0.1'
